version: '2'

services:
  mongodb:
    image: 'bitnami/mongodb:4.0'
    ports:
      # To avoid conflicts with the local mongodb server
      - 15000:27017

  express:
    tty: true # Enables debugging capabilities when attached to this container.
    image: 'bitnami/express:4'
    # command: npm start
    # See this link to understand why i've added the -L flag to the development script
    # https://www.npmjs.com/package/nodemon#application-isnt-restarting
    # https://stackoverflow.com/questions/23927195/nodemon-not-working-properly
    command: npm run development
    environment:
      - PORT=3000
      - NODE_ENV=development
      - DATABASE_URL=mongodb://mongodb:27017/the-notes-app

      - SKIP_DB_WAIT=0
      - SKIP_DB_MIGRATION=0
      - SKIP_NPM_INSTALL=0
      - SKIP_BOWER_INSTALL=0
    depends_on:
      - mongodb
    ports:
      - 3000:3000
    volumes:
      - .:/app
